### ISSUE TITLE
В оценках нужно хранить и отображать пользователя, который её поставил

### ISSUE THREAD

**Issue by sreym** [fkn/ndo#5]
![image](https://user-images.githubusercontent.com/2269530/34321341-69d65db2-e847-11e7-8add-620d458561b0.png)

**Comment by k0nagaya** [comment]
**_

> I TOKE THIS

_**

**Comment by sreym** [comment]
В БД, вроде, всё хранится как надо. Нужно лишь отобразить автора оценки в списке оценок.
